openapi: 3.0.0
info:
  title: Appointments API
  description: Calendar API information
  version: 1.0.0
  contact:
    email: azer.gurbanow@gmail.com
servers:
  - url: "http://localhost:5000/api/v1"
    description: Appointment's server

tags:
  - name: Calendars
    description: Calendars managing APIs
  - name: Events
    description: Events managing APIs

components:
  schemas:
    EventBody:
      type: object
      properties:
        id:
          type: number
        # providerEmail:
        # type: string
        description:
          type: string
        subscriberName:
          type: string
          description: subscriber's firstname and lastname
        subscriberPhoneNumber:
          type: string
      required:
        # - providerEmail
        - eventId
        - subscriberName
        - subscriberPhoneNumber

    Event:
      type: object
      properties:
        id:
          type: integer
        eventId:
          type: string
        intervalId:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        meetingLink:
          type: string
        meetingDuration:
          type: integer
        subscriberName:
          type: string
        subscriberPhoneNumber:
          type: string
        summary:
          type: string
          description: The name and phone number of the person who booked the appointment
        description:
          type: string
        guests:
          type: string
        status:
          type: string
          enum:
            - booked
            - free
        appRecordStatus:
          type: integer
          default: -1
        userId:
          type: integer
          description: The provider to whom appointments belong
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    FreeSlot:
      type: object
      properties:
        id:
          type: integer
        eventId:
          type: string
        intervalId:
          type: string
        summary:
          type: string
          example: Free Slot
        description:
          type: string
          example: Free for an appointment
        provider:
          type: string
          description: The name to whom calendar belongs
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        status:
          type: string
          example: free
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    TimeInterval:
      type: object
      properties:
        intervals:
          type: array
          items:
            type: object
            properties:
              startDateTime:
                type: string
                format: date-time
              endDateTime:
                type: string
                format: date-time

    CalendarRequestBody:
      type: object
      properties:
        email:
          type: string
        id:
          type: integer
          format: int32
      required:
        - email
        - id

    GoogleCalendar:
      type: object
      properties:
        id:
          type: string
        provider:
          type: string
        description:
          type: string
        timeZone:
          type: string
        accessRole:
          type: string

    ProviderCalendar:
      type: object
      properties:
        aclId:
          type: string
        userId:
          type: string
        calendarId:
          type: string

paths:
  /getEventsList:
    get:
      summary: Returns the list of all events
      tags:
        - Events
      description: Sends provider's email to the server and retrieves the events list. If sender is a provider the list contains both free and booked events. If user is a subscriber the list contains only free events.
      responses:
        "200":
          description: A JSON array of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error

  /getAppointmentSlots:
    get:
      summary: Returns the list of all events
      tags:
        - Events
      description: Sends provider's email to the server and retrieves the list of freeSlots suitable for appointments.
      parameters:
        - name: email
          in: query
          description: The email of the provider
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A JSON array of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FreeSlot"
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error

  /createAppointmentSlots:
    post:
      summary: Returns the message about created appointment slots
      tags:
        - Events
      description: Sends user's pre-defined free time intervals to the server and retrieves the list of created free slots.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
              $ref: "#/components/schemas/TimeInterval"

      responses:
        "200":
          description: Success message of how many free appointment slots were created
          content:
            application/json:
              schema:
                type: string
                example: 5 free appointment slots were succesfully created
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error

  /createEvent:
    patch:
      summary: Creates an event on a free appointment slot
      tags:
        - Events
      description: Sends customer's details and creates an event by updating a selected free slot by Id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EventBody"

      responses:
        "200":
          description: A JSON object of the created event
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Event"
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error

  /getCalendarList:
    get:
      summary: Returns the list of calendars
      tags:
        - Calendars
      description: Retrieves the list of all calendars integrated with the service account.
      responses:
        "200":
          description: A JSON array of calendars
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GoogleCalendar"
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error

  /getAclList:
    get:
      summary: Returns the list of calendars that have access to the user's calendar
      tags:
        - Calendars
      description: Sends the user's calendarId to the server and retrieves the list of calendars that have access to the user's calendar.
      responses:
        "200":
          description: A JSON array of calendars
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Calendar"
        "404":
          description: Not found
        "500":
          description: Internal server error

  /createCalendar:
    post:
      summary: Create a calendar for a registered user
      tags:
        - Calendars
      description: Sends user's email and id to the server, creates a calendar, shares that calendar with the user, and sets the newly created calendar's id to the user's data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CalendarRequestBody"
      responses:
        "200":
          description: A JSON of the provider's calendar
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProviderCalendar"
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error

  /deleteAccess:
    delete:
      summary: Deletes the rule that has access to the user's calendar
      tags:
        - Calendars
      description: Sends the provider's calendarId and ruleId to the server and deletes the rule that has access to the provider's calendar. By that that provider will lose access to that calendar.
      responses:
        "204":
        description: Deletion successful
        "400":
          description: Bad request
        "404":
          description: Not found
        "500":
          description: Internal server error
